import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Static Asset Sep</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <Link
            href="/local"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Local Image <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Image optimization with an image from `public` folder.
            </p>
          </Link>

          <Link
            href="/remote"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Remote Image <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Image optimization with a remote image
            </p>
          </Link>

          <Link
            href="/presigned"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Presigned URL <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Image optimization with a remote iamge from a presigned URL.
            </p>
          </Link>

          <div
            className={styles.card}
          >
            <h2 className={inter.className}>
              Heavy Images <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              <Link href={"/heavy/abenezer"}>Abenezer</Link> - 
              <Link href={"/heavy/samsung1"}>Samsung1</Link> - 
              <Link href={"/heavy/samsung12"}>Samsung2</Link> - 
              <Link href={"/heavy/swainson"}>Swainson</Link>
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
